const f = ()=>{

try{
    let a = 0
   console.log(program)
    console.log("Program ran successfully")
}
catch(err){
    console.log("This is an error")
    console.log(p
    )
}
finally{
    console.log("I am a good boy")
    // close the file
    // exit the loop
    // write to the log file
  }
}
f()